# Generated by Django 4.2.2 on 2023-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='library',
            field=models.CharField(choices=[('The Community Library Project - Khirki', 'Tclp 01'), ('The Community Library Project - Sikanderpur', 'Tclp 02'), ('The Community Library Project - Sec 43', 'Tclp 03'), ('The Community Library Project - South Ex', 'Tclp 04')], default='The Community Library Project - Khirki', max_length=50),
        ),
    ]
