# Generated by Django 4.2.2 on 2024-06-27 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_member_id_alter_member_member_id'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['datetime']},
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_common_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_common_1', to='members.member', verbose_name='Laptop for All - 1'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_common_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_common_2', to='members.member', verbose_name='Laptop for All - 2'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_disability', to='members.member', verbose_name='Laptop for P w Disabilities'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_education', to='members.member', verbose_name='Laptop for Education'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_non_male_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_non_male_1', to='members.member', verbose_name='Laptop for Girls, T, NB - 1'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_non_male_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_non_male_2', to='members.member', verbose_name='Laptop for Girls, T, NB - 2'),
        ),
    ]
