# Generated by Django 4.2.2 on 2024-10-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_member_id_alter_member_member_id'),
        ('slots', '0002_alter_slot_options_alter_slot_laptop_common_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='laptop_adult_common_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_adult_common_1', to='members.member', verbose_name='Laptop for adults - Common'),
        ),
        migrations.AddField(
            model_name='slot',
            name='laptop_adult_non_male',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_adult_non_male', to='members.member', verbose_name='Laptop for adults - T, NB, and Women'),
        ),
    ]
