# Generated by Django 4.2.2 on 2023-07-28 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_slot_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='datetime',
        ),
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='slot',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
