# Generated by Django 4.2.2 on 2023-07-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_gender'),
        ('slots', '0004_remove_slot_date_remove_slot_time_slot_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
