# Generated by Django 4.2.2 on 2023-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0005_alter_slot_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='laptop',
            field=models.CharField(choices=[('Common Laptop - 1', 'Common Laptop - 1'), ('Common Laptop - 2', 'Common Laptop - 2'), ('Laptop for girls and Trans members - 1', 'Laptop for girls and Trans members - 1'), ('Laptop for girls and Trans members - 2', 'Laptop for girls and Trans members - 2'), ('Laptop for education', 'Laptop for education'), ('Laptop for disabled', 'Laptop for disabled')], default='Common Laptop - 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='slot',
            name='library',
            field=models.CharField(choices=[('The Community Library Project - Khirki', 'The Community Library Project - Khirki'), ('The Community Library Project - Sikanderpur', 'The Community Library Project - Sikanderpur'), ('The Community Library Project - South Ex', 'The Community Library Project - South Ex')], default='The Community Library Project - Khirki', max_length=50),
        ),
    ]
