# Generated by Django 4.2.2 on 2024-11-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0005_populate_member_uid_fks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='laptop_adult_common_1',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='laptop_adult_non_male',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='laptop_common_1',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='laptop_common_2',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='laptop_disability',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='laptop_education',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='laptop_non_male_1',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='laptop_non_male_2',
        ),
    ]
