# Generated by Django 4.2.2 on 2024-11-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0006_remove_slot_laptop_adult_common_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='laptop_adult_common_1_uid',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptop_adult_common_1_uid_slots', to='members.member', verbose_name='Laptop for adults - Common',
                to_field='uid',
            ),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_adult_non_male_uid',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptop_adult_non_male_uid_slots', to='members.member', verbose_name='Laptop for adults - T, NB, and Women',
                to_field='uid',
            ),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_common_1_uid',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptop_common_1_uid_slots', to='members.member', verbose_name='Laptop for All - 1',
                to_field='uid',
            ),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_common_2_uid',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptop_common_2_uid_slots', to='members.member', verbose_name='Laptop for All - 2',
                to_field='uid',
            ),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_disability_uid',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptop_disability_uid_slots', to='members.member', verbose_name='Laptop for P w Disabilities',
                to_field='uid',
            ),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_education_uid',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptop_education_uid_slots', to='members.member', verbose_name='Laptop for Education',
                to_field='uid',
            ),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_non_male_1_uid',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptop_non_male_1_uid_slots', to='members.member', verbose_name='Laptop for Girls, T, NB - 1',
                to_field='uid',
            ),
        ),
        migrations.AlterField(
            model_name='slot',
            name='laptop_non_male_2_uid',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptop_non_male_2_uid_slots', to='members.member', verbose_name='Laptop for Girls, T, NB - 2',
                to_field='uid',
            ),
        ),
    ]
