# Generated by Django 4.2.2 on 2024-11-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0007_alter_slot_laptop_adult_common_1_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='laptop_adult_common_1_uid',
            new_name='laptop_adult_common_1',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='laptop_adult_non_male_uid',
            new_name='laptop_adult_non_male',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='laptop_common_1_uid',
            new_name='laptop_common_1',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='laptop_common_2_uid',
            new_name='laptop_common_2',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='laptop_disability_uid',
            new_name='laptop_disability',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='laptop_education_uid',
            new_name='laptop_education',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='laptop_non_male_1_uid',
            new_name='laptop_non_male_1',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='laptop_non_male_2_uid',
            new_name='laptop_non_male_2',
        ),
    ]
