# Generated by Django 4.2.2 on 2024-11-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0006_remove_member_id_alter_member_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.CharField(choices=[('The Community Library Project - Khirki', 'The Community Library Project - Khirki'), ('The Community Library Project - Sikanderpur', 'The Community Library Project - Sikanderpur'), ('The Community Library Project - South Ex', 'The Community Library Project - South Ex')], max_length=50)),
                ('entered_date', models.DateField(auto_now_add=True)),
                ('entered_time', models.TimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_logs', to='members.member')),
            ],
        ),
    ]
