# Generated by Django 4.2.2 on 2024-11-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrylog', '0004_alter_entrylog_member_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrylog',
            old_name='member_uid',
            new_name='member',
        )
    ]
