# Generated by Django 4.2.2 on 2024-11-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrylog', '0005_remove_entrylog_member_uid_entrylog_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_logs', to='members.member', to_field='uid'),
        ),
    ]
