# Generated by Django 4.2.2 on 2024-11-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_member_unique_uppercase_member_id'),
        ('entrylog', '0006_alter_entrylog_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_logs', to='members.member'),
        ),
    ]
