# Generated by Django 4.2.2 on 2023-07-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_gender'),
    ]

    operations = [
    ]
