# Generated by Django 4.2.2 on 2023-07-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20230731_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Gender non-conforming', 'Gender Non Conforming'), ('Non-binary', 'Non Binary'), ('Prefer not to say', 'Prefer Not To Say'), ('Transgender', 'Transgender')], default='Female', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.TextField(null=True),
        ),
    ]
