# Generated by Django 4.2.2 on 2023-08-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_age_alter_member_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
