# Generated by Django 4.2.2 on 2024-11-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_populate_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='uid',
            field=models.UUIDField(default=None, editable=False, null=True, unique=True),
        ),
    ]
