# Generated by Django 4.2.2 on 2024-11-24 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entrylog', '0006_alter_entrylog_member'),
        ('slots', '0008_remove_slot_laptop_adult_common_1_uid_and_more'),
        ('members', '0009_alter_member_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
