# Generated by Django 4.2.2 on 2024-11-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_member_member_id_alter_member_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
