# Generated by Django 4.2.2 on 2024-11-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_cyber_project_enabled_member_first_login_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
