# Generated by Django 4.2.2 on 2024-12-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_member_first_login_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
